name: Auto Video Generator

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install FFmpeg & Run Script
        run: |
          sudo apt-get update && sudo apt-get install -y ffmpeg python3-pip
          pip install gTTS --break-system-packages
          python3 script.py
